apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/homepage_static
    server: 10.100.0.100 
